package com.Wsdl2Code.WebServices.SampleService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.2
//
// Date Of Creation: 2/20/2013 11:16:36 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.SampleService.VectorByte;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Request implements KvmSerializable {
	
    public String companyId;
    public String userName;
    public String password;
    public VectorByte byteArray;
    
    public Request(){}
    
    public Request(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("companyId"))
        {
            Object obj = soapObject.getProperty("companyId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("companyId");
                companyId = j.toString();
            }
        }
        if (soapObject.hasProperty("userName"))
        {
            Object obj = soapObject.getProperty("userName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("userName");
                userName = j.toString();
            }
        }
        if (soapObject.hasProperty("Password"))
        {
            Object obj = soapObject.getProperty("Password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Password");
                password = j.toString();
            }
        }
        if (soapObject.hasProperty("byteArray"))
        {
            SoapPrimitive j = (SoapPrimitive)soapObject.getProperty("byteArray");
            byteArray = new VectorByte(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return companyId;
            case 1:
                return userName;
            case 2:
                return password;
            case 3:
                return byteArray.toString();
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "companyId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "userName";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Password";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "byteArray";
                break;
        }
}

@Override
public void setProperty(int arg0, Object arg1) {
}

}
