package com.Wsdl2Code.WebServices.SampleService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.2
//
// Date Of Creation: 2/20/2013 11:16:36 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class WSAddress implements KvmSerializable {
    
    public String city;
    public String street;
    public int number;
    public int zipcode;
    
    public WSAddress(){}
    
    public WSAddress(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("City"))
        {
            Object obj = soapObject.getProperty("City");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("City");
                city = j.toString();
            }
        }
        if (soapObject.hasProperty("Street"))
        {
            Object obj = soapObject.getProperty("Street");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Street");
                street = j.toString();
            }
        }
        if (soapObject.hasProperty("number"))
        {
            Object obj = soapObject.getProperty("number");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("number");
                number = Integer.parseInt(j.toString());
            }
        }
        if (soapObject.hasProperty("zipcode"))
        {
            Object obj = soapObject.getProperty("zipcode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("zipcode");
                zipcode = Integer.parseInt(j.toString());
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return city;
            case 1:
                return street;
            case 2:
                return number;
            case 3:
                return zipcode;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "City";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Street";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "number";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "zipcode";
                break;
        }
}

@Override
public void setProperty(int arg0, Object arg1) {
}

}
